baseURL = "https://urssi.us/"
relativeURLs = true
languageCode = "en-us"
title = " Website of the US Research Software Sustainability Institute"
theme = ["urssi", "hugo-easy-gallery"]

googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
footnotereturnlinkcontents = "â†©"

pagination.pagerSize = 4
pagination.path = "page"
rssLimit = 20

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
