baseURL = "http://urssi.us/"
languageCode = "en-us"
title = "Official Website of the US Research Software Sustaiability Institute"
theme = "urssi"

googleAnalytics = "UA-462421-7"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
footnotereturnlinkcontents = "â†©"

paginate = 5
paginatePath = "page"
rssLimit = 20

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
